version: "3.3"
services:
  bunkr.api.rest:
    build: "."
    ports:
      - "5000"
    restart: "always"
    networks: 
      - "bunkr.network"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bunkr.api.rest
    ports:
      - "5000:5000"
    networks: 
      - "bunkr.network"
networks:
  bunkr.network: